title: Pedro Rivero
description: Sailing Logbook
baseurl: "" # Change to "/repo-name" for project pages
url: "https://pedrorivero.github.io" # Update to your actual URL
theme: minima
markdown: kramdown

# Include additional files for GitHub Pages
include:
  - LICENSE-APACHE.md
  - LICENSE-CC.md