title: Pedro Rivero’s Personal Website
description: Sharing projects, passions, and ideas.
baseurl: "" # Change to "/repo-name" for project pages
url: "https://pedrorivero.github.io" # Update to your actual URL
theme: minima
markdown: kramdown

# Custom collections
collections:
  sailing:
    output: true
    permalink: /sailing/:name/

# Include additional files for GitHub Pages
include:
  - LICENSE-APACHE.md
  - LICENSE-CC.md